"""add funded_amount to loans

Revision ID: b96b8e8aa2e5
Revises: e7bf9c74dc1f
Create Date: 2026-08-25 21:04:18.797902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96b8e8aa2e5'
down_revision: Union[str, Sequence[str], None] = 'e7bf9c74dc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('funded_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'funded_amount')
    # ### end Alembic commands ###
